apiVersion: apps/v1
kind: Deployment
metadata:
  name: automacao-pmo-frontend
  namespace: qas-automacao-pmo-tin
  labels:
    app: automacao-pmo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automacao-pmo-frontend
  template:
    metadata:
      labels:
        app: automacao-pmo-frontend
    spec:
      containers:
      - name: frontend
        image: registry-docker.weg.net/din/tin/automacao_pmo/automacaopmofrontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: automacao-pmo-frontend-configmap
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: automacao-pmo-frontend-service
  namespace: qas-automacao-pmo-tin
spec:
  selector:
    app: automacao-pmo-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
