import { AppBar, Box, Container, IconButton, Toolbar, Typography } from "@mui/material";
import ExitToAppIcon from '@mui/icons-material/ExitToApp';
import { auth, signIn } from "@/app/auth";
import { signOut } from "@/app/auth";
import { redirect } from "next/navigation";
export default async function Home() {
        const session = await auth();

        if (session) {
            if (session?.error === "RefreshAccessTokenError") {
                signIn("keycloak", { redirectTo: "/" });
            }
        return (
            <Box sx={{ flexGrow: 1 }}>
                <AppBar position="static" sx={{ mb: 6 }}>
                    <Toolbar>
                        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                            {"automacao-pmo-frontend"}
                        </Typography>
                        <Typography component="h4" sx={{ mr: 3, fontWeight: "bold" }}>
                            Welcome, {session.user?.name}
                        </Typography>
                        <form action={async () => {
                            "use server"
                            await signOut({
                                redirectTo: "/login"
                            })
                        }}>
                            <IconButton type="submit" sx={{ color: "#fff" }}>
                                <ExitToAppIcon />
                            </IconButton>
                        </form>
                    
                        </Toolbar>
                </AppBar>
                <Container sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center"
                }}>
                    <Typography component="p">
                        Home page to project generated by Developers Suite Code Generator.
                    </Typography>
                </Container>
            </Box >
        );
        } else {
            redirect("/login")
        }
        }